[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Configuração de velocidade do Monitor Serial (de acordo com o seu Serial.begin(115200))
monitor_speed = 115200

; Configuração de velocidade de upload (deixa a gravação bem mais rápida)
upload_speed = 921600

; Dependências de bibliotecas (essenciais para compilar o DHT.h)
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14